require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions:
    rubocop-rake: false

  Exclude:
    - db/migrate/**/*
    - db/schema.rb
    - config/**/*
    - bin/**/*
    - node_modules/**/*
    - Gemfile
    - Rakefile

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: true

Layout/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Rails/HasAndBelongsToMany:
  Enabled: true
